name: Auto Tag

on:
  push:
    branches:
      - master
      - '**'

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to access all tags

      - name: Create tag using commit message
        id: tagger
        uses: mathieudutour/github-tag-action@v6.1
        with:
          tag_prefix: 'v'
          default_bump: 'patch'
          default_prerelease_bump: 'prerelease'
          dry_run: true  # Set to true for testing, change to false for actual tagging
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print new tag
        run: |
          echo "Tagged version: ${{ steps.tagger.outputs.new_tag }}"
