name: Run Tests and Notify Discord

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/codegen-and-test

  pr-notification:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Extract PR Metadata
        uses: actions/github-script@v6
        id: get_pr_data
        with:
          script: |
            const pr = context.payload.pull_request;
            core.setOutput('title', pr.title);
            core.setOutput('body', pr.body);
            core.setOutput('url', pr.html_url);

      - name: Debug PR Data Outputs
        run: |
          echo "Title: ${{ steps.get_pr_data.outputs.title }}"
          echo "Body: ${{ steps.get_pr_data.outputs.body }}"
          echo "URL: ${{ steps.get_pr_data.outputs.url }}"

      - uses: ./.github/actions/discord-webhook
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          pr-title: ${{ steps.get_pr_data.outputs.title }}
          pr-body: ${{ steps.get_pr_data.outputs.body }}
          pr-url: ${{ steps.get_pr_data.outputs.url }}
